apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod-0-1
spec:
  replicas: 1368
  selector:
    matchLabels:
      labelc1: labelc2
  template:
    metadata:
      name: nginx-replica-set
      labels:
        labelc1: labelc2
    spec:
      schedulerName: poseidon
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Ki"
            cpu: "2m"
          limits:
            memory: "8Ki"
            cpu: "4m"
