apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod-affinity-pod-0-12
spec:
  replicas: 1000
  selector:
    matchLabels:
      labeld1: labeld2
  template:
    metadata:
      name: nginx-replica-set
      labels:
        labeld1: labeld2
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: labelc1
                operator: In
                values:
                - labelc2
            topologyKey: kubernetes.io/hostname
#      schedulerName: poseidon
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "3Mi"
            cpu: "1m"
          limits:
            memory: "6Mi"
            cpu: "6m"
