apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod
spec:
  replicas: replicas_string
  selector:
    matchLabels:
      key: value
  template:
    metadata:
      name: nginx-replica-set
      labels:
        key: value
    spec:
#      schedulerName: poseidon
      nodeSelector:
        key: value
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "memreq"
            cpu: "cpureq"
          limits:
            memory: "memlim"
            cpu: "cpulim"
