apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod-0-1
spec:
  replicas: 1000
  selector:
    matchLabels:
      labelc1: labelc2
  template:
    metadata:
      name: nginx-replica-set
      labels:
        labelc1: labelc2
    spec:
#      schedulerName: poseidon
      nodeSelector:
        labela1: labela2
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Mi"
            cpu: "2m"
          limits:
            memory: "8Mi"
            cpu: "4m"
