apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod-165-1
spec:
  replicas: 1
  selector:
    matchLabels:
      key165: value165
  template:
    metadata:
      name: nginx-replica-set
      labels:
        key165: value165
    spec:
#      schedulerName: poseidon
      nodeSelector:
        key165: value165
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Ki"
            cpu: "2m"
          limits:
            memory: "8Ki"
            cpu: "6m"
