apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: nginx-pod-affinity-pod-113-3
spec:
  replicas: 19
  selector:
    matchLabels:
      labeld1: labeld2
  template:
    metadata:
      name: nginx-replica-set
      labels:
        labeld1: labeld2
    spec:
      schedulerName: poseidon
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: key113
                operator: NotIn
                values:
                - value113
      containers:
      - name: nginx
        image: "nginx:1.11.1-alpine"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "4Ki"
            cpu: "2m"
          limits:
            memory: "8Ki"
            cpu: "6m"
